# Generated by Django 5.0.2 on 2024-03-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lrn',
            new_name='lrn_or_tid',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tid',
        ),
    ]
