# Generated by Django 5.0.2 on 2024-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_useraccount_options_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='lrn_or_tid',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
