# Generated by Django 5.0.2 on 2024-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_useraccount_mastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='posttest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pretest',
            field=models.IntegerField(null=True),
        ),
    ]
