# Generated by Django 5.0.2 on 2024-05-01 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_useraccount_posttest_useraccount_pretest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act1Module1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.TextField(max_length=600)),
                ('median', models.TextField(max_length=600)),
                ('mode', models.TextField(max_length=600)),
                ('feedbacks', models.TextField(max_length=600, null=True)),
                ('grade', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
