# Generated by Django 5.0.2 on 2024-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_act1module1'),
    ]

    operations = [
        migrations.AddField(
            model_name='act1module1',
            name='status',
            field=models.CharField(default='submitted', max_length=50),
        ),
    ]
