# Generated by Django 5.0.2 on 2024-05-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_act1module1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='assessment',
            field=models.CharField(max_length=250),
        ),
    ]
