# Generated by Django 5.0.2 on 2024-05-01 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_score_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assessment'),
        ),
    ]
