# Generated by Django 5.0.2 on 2024-05-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_score_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type_of',
            field=models.CharField(choices=[('formative', 'FORMATIVE'), ('post_test', 'POST-TEST'), ('pre_test', 'PRE-TEST'), ('mastery', 'MASTERY')], max_length=50),
        ),
    ]
