# Generated by Django 5.0.2 on 2024-05-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='files',
            field=models.FileField(null=True, upload_to='activity_files'),
        ),
    ]
