# Generated by Django 5.0.2 on 2024-05-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_act_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='feedback',
            field=models.TextField(max_length=660, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='remarks',
            field=models.TextField(max_length=260, null=True),
        ),
    ]
